version: '3.7'

services:
  nginx:
    build:
      context: .
      args:
        NGINX_IMAGE: ${NGINX_IMAGE}
      dockerfile: ./docker-config/nginx-base/Dockerfile
    image: '${COMPOSE_PROJECT_NAME}-nginx'
    env_file: &env
      - src/.env
    links:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./src/web:/var/www/src/web:consistent
  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build:
      context: .
      args:
        PHP_IMAGE: ${PHP_IMAGE}
      dockerfile: ./docker-config/php/Dockerfile
    image: '${COMPOSE_PROJECT_NAME}-php'
    depends_on:
      - "postgres"
      - "mariadb"
      - "redis"
    env_file:
      *env
    expose:
      - "9000"
    links:
      - postgres
      - mariadb
      - redis
    volumes:
      - ./src:/var/www/src:cached
      - ./src/vendor:/var/www/src/vendor:delegated
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}
    env_file:
      *env
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: app
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgsql-data:/var/lib/postgresql/data
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}
    env_file:
      *env
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_USER: app
      MYSQL_PASSWORD: letmein
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: ${REDIS_IMAGE}
    expose:
      - "6379"
    volumes:
      - redis-data:/data
  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}-adminer
    image: ${ADMINER_IMAGE}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - "postgres"
      - "mariadb"

volumes:
  mysql-data:
  pgsql-data:
  redis-data: